spring.application.name=Fullstack
spring.data.mongodb.uri=mongodb+srv://root:6YnrPQYazDlWHp81@cluster0.qfdowrr.mongodb.net/eventdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=eventdb