spring.application.name=Fullstack
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE:eventdb}
jwt.secret=${JWT_SECRET}
